apiVersion: v1
kind: Service
metadata:
  labels:
    app: managedidentity
  name: managedidentity
  namespace: managedidentity
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: managedidentity
  type: LoadBalancer
