apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    azure.workload.identity/client-id: a989b88b-dedc-4c1b-a41a-348f0eaba176 # id of azure user managed identity
  name: cluster-workload-user
  namespace: managedidentity
